version: "3.7"

services:

  web:
    container_name: mission_controll_web
    build: .
    ports:
      - "${WEB_PORT}:80"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    volumes:
      - type: bind
        source: ../../
        target: /usr/src/app
        consistency: ${FILE_SYSTEM_MODE:-delegated}

networks:
  default:
    external:
      name: nproxy
